export {default as Sidebar} from "../components/sidebar/SIdebar"
export {default as Main} from "../components/main/Main"
export {default as Layout} from "../components/layout/Layout"
export {default as Map} from "./info/Info"
export {default as Info } from "../components/info/Info"
export {default as Getting} from "../components/getting/Getting"